"""PDF report exporter using ReportLab."""

from __future__ import annotations

from pathlib import Path
from uscan.scanner.models import ScanReport, ScanStatus


class PDFExporter:
    @staticmethod
    def export(report: ScanReport, output_path: Path) -> Path:
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.colors import HexColor
            from reportlab.lib.units import mm
            from reportlab.platypus import (
                SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer,
            )
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        except ImportError:
            raise RuntimeError(
                "PDF export requires reportlab. Install with: pip install uscan[pdf]"
            )

        output_path.parent.mkdir(parents=True, exist_ok=True)

        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=A4,
            topMargin=20 * mm,
            bottomMargin=20 * mm,
            leftMargin=15 * mm,
            rightMargin=15 * mm,
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "USCANTitle",
            parent=styles["Title"],
            textColor=HexColor("#dc2626"),
            fontSize=28,
            spaceAfter=4,
        )
        subtitle_style = ParagraphStyle(
            "USCANSubtitle",
            parent=styles["Normal"],
            textColor=HexColor("#6b7280"),
            fontSize=10,
            spaceAfter=20,
            alignment=1,
        )
        heading_style = ParagraphStyle(
            "USCANHeading",
            parent=styles["Heading2"],
            textColor=HexColor("#dc2626"),
            fontSize=14,
            spaceBefore=16,
            spaceAfter=8,
        )
        normal = styles["Normal"]

        elements = []

        elements.append(Paragraph("USCAN", title_style))
        elements.append(Paragraph("Username Intelligence Report", subtitle_style))
        elements.append(Spacer(1, 10))

        meta_data = [
            ["Target", report.username],
            ["Date", report.started_at.strftime("%Y-%m-%d %H:%M:%S UTC")],
            ["Platforms Checked", str(report.platforms_checked)],
            ["Duration", f"{report.duration_seconds}s"],
        ]
        meta_table = Table(meta_data, colWidths=[120, 350])
        meta_table.setStyle(TableStyle([
            ("TEXTCOLOR", (0, 0), (0, -1), HexColor("#6b7280")),
            ("TEXTCOLOR", (1, 0), (1, -1), HexColor("#1a1a1a")),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        elements.append(meta_table)
        elements.append(Spacer(1, 10))

        elements.append(Paragraph("Summary", heading_style))
        summary_data = [
            ["Found", str(report.summary.found)],
            ["Not Found", str(report.summary.not_found)],
            ["Unknown", str(report.summary.unknown)],
            ["Errors", str(report.summary.errors)],
        ]
        summary_table = Table(summary_data, colWidths=[120, 350])
        summary_table.setStyle(TableStyle([
            ("TEXTCOLOR", (0, 0), (0, -1), HexColor("#6b7280")),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(summary_table)

        found = [r for r in report.results if r.status == ScanStatus.FOUND]
        if found:
            elements.append(Spacer(1, 10))
            elements.append(Paragraph("Discovered Profiles", heading_style))

            table_data = [["Platform", "Confidence", "Profile URL"]]
            for r in found:
                url = r.profile_url or "—"
                if len(url) > 55:
                    url = url[:52] + "..."
                table_data.append([r.platform, r.confidence.value, url])

            result_table = Table(table_data, colWidths=[120, 80, 270])
            result_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), HexColor("#1a1a1a")),
                ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#dc2626")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#e5e5e5")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#ffffff"), HexColor("#f9fafb")]),
            ]))
            elements.append(result_table)

        elements.append(Spacer(1, 30))
        elements.append(Paragraph(
            f"Generated by USCAN v{report.version}",
            ParagraphStyle("Footer", parent=normal, textColor=HexColor("#9ca3af"), fontSize=8, alignment=1),
        ))

        doc.build(elements)
        return output_path
