"""Plain text report exporter."""

from __future__ import annotations

from pathlib import Path

from uscan.scanner.models import ScanReport, ScanStatus


class TXTExporter:
    @staticmethod
    def export(report: ScanReport, output_path: Path) -> Path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        lines: list[str] = []

        lines.append("=" * 60)
        lines.append("  USCAN — Username Intelligence Report")
        lines.append("=" * 60)
        lines.append("")
        lines.append(f"  Target:      {report.username}")
        lines.append(f"  Date:        {report.started_at.strftime('%Y-%m-%d %H:%M:%S UTC')}")
        lines.append(f"  Platforms:   {report.platforms_checked}")
        lines.append(f"  Duration:    {report.duration_seconds}s")
        lines.append("")
        lines.append("-" * 60)
        lines.append("  SUMMARY")
        lines.append("-" * 60)
        lines.append(f"  Found:       {report.summary.found}")
        lines.append(f"  Not Found:   {report.summary.not_found}")
        lines.append(f"  Unknown:     {report.summary.unknown}")
        lines.append(f"  Errors:      {report.summary.errors}")
        lines.append("")

        found = [r for r in report.results if r.status == ScanStatus.FOUND]
        if found:
            lines.append("-" * 60)
            lines.append("  DISCOVERED PROFILES")
            lines.append("-" * 60)
            for r in found:
                lines.append(f"  [{r.confidence.value:6}] {r.platform:<20} {r.profile_url}")
            lines.append("")

        errors = [r for r in report.results if r.status in (ScanStatus.ERROR, ScanStatus.BLOCKED, ScanStatus.RATE_LIMITED)]
        if errors:
            lines.append("-" * 60)
            lines.append("  ERRORS / ISSUES")
            lines.append("-" * 60)
            for r in errors:
                lines.append(f"  {r.platform:<20} {r.status.value:<15} {r.error or ''}")
            lines.append("")

        lines.append("=" * 60)
        lines.append(f"  Generated by USCAN v{report.version}")
        lines.append("=" * 60)

        output_path.write_text("\n".join(lines), encoding="utf-8")
        return output_path
